%% Gaussian Profile
clc;
E=input('Energy of each pulse in mJ:\n');
t=input('Pulse duration in ns:\n');
L=input('Wavelength of Laser Light in nm:\n');
M=input('Beam Quality Factor:\n');
f=input('Focal distance in mm:\n');
D=input('Beam diameter in mm:\n');
Z=input('Wave impedance in ohm:\n');
n0=input('Refractive index of the medium\n');
w0=((2*f*10^-3*L*10^-9*M)/(pi*10*D*10^-3));
d0=2*w0*10^6;
fprintf('The Spot Size = %.6f micro-meter\n',d0);
E0=sqrt((2*(E*10^6/t)/(pi*w0^2))/(3*10^8*n0^-1*8.854*10^-12));
fprintf('Electric field amplitude = %.6f V/m \n',E0);
z0=(pi/(L*M))*10^9*w0^2*n0;
Rd=z0*1000;
fprintf('Rayleigh Distance = %.6f mm\n',Rd);
P=(0.5*(E0)^2*n0*pi*w0^2)/(2*Z);
fprintf('Total power crossing any plane = %.6f W\n',P);
[x,y]=meshgrid(-0.0001:0.000001:0.0001);
k=(2*pi)/(L*10^-9);
z=input('Distance of the plane from the beam waist in mm:(hint:more close non zero values will provide approximately the beam waist)\n');
z=z./1000;
w=w0*sqrt(1+(z/z0).^2);
fprintf('Beam Diameter = %.6f mm \n',2*w*1000);
FWHM=sqrt(2*log(2)).*w*1000;
fprintf('The Full Width at Half Maximum (FWHM) = %.6f mm\n',FWHM);
R=z.*(1+(z0/z).^2);
fprintf('Radius of Curvature = %.6f mm\n',R*1000);
E=(w0./w).*exp(-(x.^2+y.^2)/(w).^2).*exp(-(k.*(x.^2+y.^2))/(2.*R));
Ia=(2*P/(pi*w.^2))*exp(-(2.*(x.^2+y.^2))/(w.^2));
I=(2*P/(pi*w.^2))*exp(-(2.*(x.^2+y.^2))/(w.^2))*10^-13*0.73888;
figure(1);
contour3(E,1000);
xlabel('Number of grids in X direction');
ylabel('Number of grids in Y direction');
colorbar;
colormap hsv;
title(['Intensity distribution at ',num2str(z.*1000),' mm from beam waist']);
figure(2);
contour(E,300);
xlabel('Number of grids in X direction');
ylabel('Number of grids in Y direction');
colorbar;
colormap hsv;
title(['Intensity distribution at ',num2str(z.*1000),' mm from beam waist']);
figure(3);
plot(x,E);
xlabel('Number of grids in X direction');
ylabel('Intensity Distribution');
title(['Intensity distribution at ',num2str(z.*1000),' mm from beam waist']);
figure(4);
plot(x,I);
xlabel('Number of grids in X direction');
ylabel('Power Distribution (GW/cm^2)');
title(['Power distribution at ',num2str(z.*1000),' mm from beam waist']);
%% End of MATLAB Program